import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavList from "@/components/NavList";
import { Inter } from "next/font/google";
import pageContent from "@/data/qa";
import { useRouter } from "next/router";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const QuestionPage = () => {
  const router = useRouter();
  const { qid } = router.query;
  const pc = pageContent.find((qa) => qa.id === +qid);
  if (pc) {
    return (
      <>
        <Head>
          <title>Senior CSE Practice Test - Question {pc.id}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.description}>
            <Link href="/">&larr; Back Home</Link>
          </div>
          <div className={styles.center}>
            <div className={styles.description}>
              <p>{pc.question}</p>
            </div>
            <div className={styles.answer}>
              <p className={inter.className}>{pc.answer}</p>
            </div>
          </div>
          <NavList />
        </main>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Senior CSE Practice Test</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.description}>
            <Link href="/">&larr; Back Home</Link>
          </div>
          <div className={styles.center}>
            <div className={styles.description}>
              <p>Invalid question</p>
            </div>
          </div>
          <NavList />
        </main>
      </>
    );
  }
};
export default QuestionPage;
