import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavList from "@/components/NavList";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  return (
    <>
      <Head>
        <title>Senior CSE Practice Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.center}>
          <p className={inter.className}>
            Select a question to find the answer
          </p>
        </div>
        <NavList />
      </main>
    </>
  );
};

export default Home;
